# Basic
title: Mapzh
subtitle: Mapzh’s Blog
description: 博客内容包含iOS、Python、Linux等
creator: <a href="http://blog.mapzh.com">@mapzh</a>

url: "http://blog.mapzh.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: atom-gray        #2D3037

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: My Projects, url: 'https://github.com/mapzh'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: 1697504115
    github: mapzh
    mail: mapzhx@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
